"""GNU Makefile generation from a build graph."""

from __future__ import annotations

from pathlib import Path

from .artifacts import Object
from .command import command_state_path, make_argv_fragment, make_recipe
from .graph import BuildGraph


def _escape(path: object) -> str:
    return str(path).replace("$", "$$").replace("#", r"\#").replace(" ", r"\ ")


def _unique(values: list[Path]) -> list[Path]:
    return list(dict.fromkeys(values))


def render(graph: BuildGraph) -> str:
    """Render a GNU Make compatible Makefile."""

    aliases = [target.name for target in graph.targets]
    if len(set(aliases)) != len(aliases):
        raise ValueError(
            "top-level artifacts must have distinct names for Make aliases"
        )

    lines = [
        "# Generated by xtc-build; do not edit.",
        ".DEFAULT_GOAL := all",
        f".PHONY: all clean {' '.join(_escape(name) for name in aliases)}",
        "",
        "all: " + " ".join(_escape(name) for name in aliases),
        "",
    ]

    for target in graph.targets:
        lines.extend(
            [
                f"{_escape(target.name)}: {_escape(target.output(graph.context))}",
                "",
            ]
        )

    depfiles: list[Path] = []
    outputs: list[Path] = []
    state_paths: list[Path] = []
    for node in graph.topological_order():
        command = graph.command(node)
        output = command.outputs[0]
        outputs.extend(command.outputs)
        state_paths.append(command_state_path(command))
        prerequisites = _unique(list(command.inputs))
        escaped_prerequisites = " ".join(_escape(path) for path in prerequisites)
        # Rebuilding a generated Makefile must also reconsider every command:
        # Make does not otherwise know that compiler or linker flags changed.
        makefile_input = "$(firstword $(MAKEFILE_LIST))"
        lines.append(
            f"{_escape(output)}: {escaped_prerequisites} {makefile_input}".rstrip()
        )
        lines.extend([make_recipe(command), ""])
        if isinstance(node, Object):
            depfiles.append(node.depfile(graph.context))

    clean_files = outputs + depfiles + state_paths
    lines.extend(
        [
            "clean:",
            "\t"
            + make_argv_fragment(("rm", "-f", *(str(path) for path in clean_files))),
            "",
        ]
    )
    if depfiles:
        lines.append("-include " + " ".join(_escape(path) for path in depfiles))
        lines.append("")
    return "\n".join(lines)


def write(graph: BuildGraph, path: str | Path) -> Path:
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(render(graph), encoding="utf-8")
    return destination
