"""Ninja build file generation from a build graph."""

from __future__ import annotations

from io import StringIO
from pathlib import Path

from ninja import ninja_syntax

from .artifacts import Object
from .command import Command, posix_recipe_fragments
from .graph import BuildGraph


def _unique_paths(paths: tuple[Path, ...]) -> list[str]:
    return [str(path) for path in dict.fromkeys(paths)]


def _command_fragment(command: Command) -> str:
    fragment = " && ".join(posix_recipe_fragments(command))
    return ninja_syntax.escape(fragment)


def render(graph: BuildGraph, build_file: str | Path) -> str:
    """Render a Ninja build file for the selected graph."""

    destination = Path(build_file)
    output = StringIO()
    writer = ninja_syntax.Writer(output)  # pyright: ignore[reportArgumentType]
    writer.comment("Generated by xtc-build; do not edit.")
    writer.newline()
    writer.rule(
        "xtc_command",
        command="$cmd",
        description="$description",
    )
    writer.rule(
        "xtc_compile",
        command="$cmd",
        description="$description",
        depfile="$depfile",
        deps="gcc",
    )

    for node in graph.topological_order():
        command = graph.command(node)
        variables = {
            "cmd": _command_fragment(command),
            "description": ninja_syntax.escape(
                f"{type(node).__name__} {command.outputs[0]}"
            ),
        }
        rule = "xtc_command"
        if isinstance(node, Object):
            rule = "xtc_compile"
            variables["depfile"] = ninja_syntax.escape(str(node.depfile(graph.context)))
        writer.build(
            outputs=[str(path) for path in command.outputs],
            rule=rule,
            inputs=_unique_paths(command.inputs),
            implicit=[str(destination)],
            variables=variables,
        )

    aliases = [target.name for target in graph.targets]
    if len(set(aliases)) != len(aliases):
        raise ValueError(
            "top-level artifacts must have distinct names for Ninja aliases"
        )
    for target in graph.targets:
        writer.build(
            outputs=[target.name],
            rule="phony",
            inputs=[str(target.output(graph.context))],
        )
    writer.default([ninja_syntax.escape_path(alias) for alias in aliases])
    return output.getvalue()


def write(graph: BuildGraph, path: str | Path) -> Path:
    """Write a Ninja build file, preserving its timestamp when unchanged."""

    destination = Path(path)
    content = render(graph, destination)
    try:
        if destination.read_text(encoding="utf-8") == content:
            return destination
    except OSError:
        pass

    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_name(destination.name + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(destination)
    return destination
